### ISSUE TITLE
Roadmap to Production

### ISSUE THREAD

**Issue by aurbano** [dotdot-im/dotdot#3]
- [x] Users persistance in DB
- [x] Bundle people in rooms (20 each or so)
- [x] Persist session in postgres
- [x] Drafts are normal messages, but they keep bumping to the bottom
- [x] Validate usernames
- [x] Set password to keep username
- [x] PM messages
- [x] Keep chat room recent messages for new joiners
- [x] Cap username length
- [x] Set up dotdot.im domain
- [x] Balance rooms over time to try to maintain the number (on connect, disconnect, timer)
- [x] Kick inactive users
- [x] Notification sounds if tab is blurred
- [x] Hide inactive users from online users list
- [x] Auto banning (spammy messages, urls..) (tmp/forever - IP/localStorage, username (block it/delete it) )
- [x] Help icon in frontend, trigger /help, add more to it
- [x] Fix mobile issues as much as possible
- [x] ADMIN: Switch to any room by cliking on them in the admin page, so we can test it
- [x] Allow logging in with an existing username if they haven't posted any messages & they are inactive

Nice to have
- [x] Add tab title notification on new message received
- [x] ReCaptcha or something against SPAM
- [x] irc-style commands for fun (/set color #abcabc -> change your color, /set password ${pwd}, /set name newname...) -> system will reply only to you
- [x] Dark/Light designs
- [x] Pick your own color
- [x] Gray-out the icon of offline users in chat
- [x] Highlight mentions if user is online
- [x] Allowing custom user icons
- [ ] Switch rooms (to any other random room) -> https://github.com/dotdot-im/dotdot/issues/15
- [ ] Delete inactive users (different times for with/out password) -> https://github.com/dotdot-im/dotdot-node/issues/9
- [ ] If logging in close to losing the account, display a banner warning
- [ ] Flagging users (hide -> eventually ban) -> https://github.com/dotdot-im/dotdot-node/issues/10
- [x] Open Source all the things! -> Getting there!
- [x] Rate limit messages (frontend + backend), relaxing limits the more you interact
- [ ] gifs -> https://github.com/dotdot-im/dotdot/issues/16
- [ ] <del>greet people from specific websites (like hn, reddit)</del>
- [ ] suggestions for mentions -> https://github.com/dotdot-im/dotdot/issues/17

**Comment by aurbano** [comment]
All the tasks that weren't already implemented have been moved to new issues and linked, so closing this now.
